### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [projectsinflight/TubeFurnace#1]
Hello!

I found your great project from https://hackaday.com/2023/08/22/start-your-semiconductor-fab-with-this-diy-tube-furnace/

Could you please add information about the license of this repository — is it allowed to copy, change and use the code in any purpose?
It would be great to see any popular open source license.

**Comment by projectsinflight** [comment]
Hey Vazhnov!

first of all, thank you so much for your support! I never really expected
that people would take notice of this stuff that I've been working on. i'm
not super familiar with the various licenses. my intent is that people can
use the tube furnace software freely as long as it's not for profit. Do you
have any idea which license might apply? If you can point me in the right
direction to some resources that i can use to figure out which license is
appropriate that would be a great help.

Thanks,
-ProjectsInFlight

**Comment by vazhnov** [comment]
My personal choice are:
* MIT license — when I want to give the maximum freedom for everyone
* GPL v3 — if I want to force forks to use the same license

But I think you should just read any of the licenses text and decide by self. This is very personal question of the license choice :)

**Comment by vazhnov** [comment]
Sorry, I didn't see this:
> freely as long as it's not for profit

Then this is not an opensource. Because OpenSource has no limits about usage. See chapter "Four essential freedoms of Free Software" in https://en.wikipedia.org/wiki/Free_and_open-source_software

**Comment by projectsinflight** [comment]
Odd, i guess if the decision is between everyone being allowed to use it
and no one then I pick everyone. I better not get an email from a
corporation asking me to do their work for free though...

**Comment by projectsinflight** [comment]
I took a long look at the various options and eventually came to the conclusion that the MIT license was the best fit for my needs. I decided that my first priority is to the hobbyists that might utilize my work and that if even one more person gets value out of this repo by me choosing MIT over GPL then that is worth it to me. I appreciate your patience and explanation.
